"""Initial migration

Revision ID: efb7dc3f0a89
Revises: 
Create Date: 2025-12-25 13:35:12.774152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efb7dc3f0a89'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Yozuv yaratilgan sana va vaqt'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Yozuv oxirgi yangilangan sana va vaqt'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Yozuv yaratilgan sana va vaqt'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Yozuv oxirgi yangilangan sana va vaqt'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('time_zone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Yozuv yaratilgan sana va vaqt'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Yozuv oxirgi yangilangan sana va vaqt'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=True),
    sa.Column('time_end', sa.DateTime(), nullable=True),
    sa.Column('repeat', sa.Text(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Yozuv yaratilgan sana va vaqt'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Yozuv oxirgi yangilangan sana va vaqt'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Yozuv yaratilgan sana va vaqt'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Yozuv oxirgi yangilangan sana va vaqt'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('offset_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Yozuv yaratilgan sana va vaqt'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Yozuv oxirgi yangilangan sana va vaqt'),
    sa.ForeignKeyConstraint(['event_id'], ['event_invites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_alerts')
    op.drop_table('event_invites')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('blacklist_tokens')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
